# Generated by Django 3.1.5 on 2021-02-01 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample_Information',
            fields=[
                ('aliquot_pk_serial', models.IntegerField(primary_key=True, serialize=False)),
                ('received_on', models.DateField()),
                ('collected_on', models.DateField()),
                ('sample_type_code', models.CharField(max_length=50)),
                ('secondary_sample_code', models.CharField(max_length=50)),
                ('sample_type', models.CharField(max_length=50)),
                ('full_sample_type_desc', models.CharField(max_length=50)),
                ('origin_aliquot_desc', models.CharField(max_length=50)),
                ('tissue_type', models.CharField(max_length=50)),
                ('specimen_category', models.CharField(max_length=50)),
                ('volume_received', models.DecimalField(decimal_places=9, max_digits=10)),
                ('volume_remaining', models.IntegerField()),
                ('alq_status', models.CharField(max_length=50)),
                ('available_flag', models.BooleanField()),
            ],
        ),
    ]
